[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino

monitor_speed = 115200

board_microros_distro = humble
board_microros_transport = serial

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SH110X

build_flags =
    -DCORE_DEBUG_LEVEL=0
